version: 0.0
Resources:
  - myLambdaFunction:
      Type: AWS::Lambda::Function
      Properties:
        Name: "tilebase-gen"
        Alias: "tilebaseGen"
        CurrentVersion: "0"
        TargetVersion: "1"
