Transform: 'AWS::Serverless-2016-10-31'
Parameters:
    OriginUrl:
        Description: "The origin url to allow CORS requests from. This will be the base URL of your static SAM website."
        Type: "String"
Resources:
    GetTiles:
        Type: AWS::Serverless::Function
        Properties:
            Handler: main.lambda_handler
            Runtime: python2.7
            CodeUri: ./
            Events:
              GetResource:
                Type: Api
                Properties:
                  Path: /tilebase
                  Method: get
